apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
spec:
  project: default
  source:
    repoURL: https://github.com/kunaldenvr/jenkins-k8s.git
    path: jenkins/app-repo.yaml
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
